version: '3.8'

services:
  mp-spdz:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PREP_DIR: ${PREP_DIR}
      PRIME: 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
